# Generated by Django 2.2.1 on 2020-04-05 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200331_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myblog',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
