# Generated by Django 2.2.1 on 2020-04-28 07:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_myblog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='myblog',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myblog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myblog',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
