# Generated by Django 2.2.1 on 2020-04-28 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200428_1237'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myblog',
            options={'ordering': ['-date', '-updated', '-timestamp']},
        ),
    ]
