# Generated by Django 2.2.1 on 2020-04-28 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200428_1244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myblog',
            options={'ordering': ['-pk', '-date', '-updated', '-timestamp']},
        ),
    ]
