# Generated by Django 2.2.1 on 2020-04-28 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200428_1245'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myblog',
            options={'ordering': ['-publish_date', '-updated', '-timestamp']},
        ),
        migrations.RenameField(
            model_name='myblog',
            old_name='date',
            new_name='publish_date',
        ),
    ]
