# Generated by Django 2.2.1 on 2020-04-28 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_myblog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myblog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
